# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="fishy"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="false"

# Disable auto-updates
DISABLE_AUTO_UPDATE=true

# Adds red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Oh-my-zsh plugins to be loaded
plugins=(git brew osx heroku vagrant)

source $ZSH/oh-my-zsh.sh

# Export a path that is appropriate for homebrew
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin

# Alias for using Sublime from the terminal
alias subl='nocorrect subl -w'

# RVM
if [ -s $HOME/.rvm/scripts/rvm ]; then
	source ~/.rvm/scripts/rvm
	export PATH=$PATH:$HOME/.rvm/bin
fi

#===== Installed apps from brew
installedapps=$(brew list)

# Play framework
if [ ! -z $(echo $installedapps | grep -o play) ]; then
	export PLAY=$(brew --prefix play)
fi

# Scala
if [ ! -z $(echo $installedapps | grep -o scala) ]; then
	export SCALA_HOME=$(brew --prefix scala)
fi

# Node
if [ ! -z $(echo $installedapps | grep -o node) ]; then
	export NODE=$(brew --prefix node)
fi

unset installedapps

# Setup zsh keybindings to work with iTerm2
bindkey -e
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

# A .profile file can be used to override with machine specific settings
if [ -e .profile ];then
	source .profile
fi

# Add RVM to PATH for scripting
PATH=$PATH:$HOME/.rvm/bin 

# Add TeXLive to the PATH
PATH=$PATH:/usr/local/texlive/2013/bin/x86_64-darwin 

# Add path based on the Postgres.app
PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin
