# Generated by chezmoi - do not edit manually
test -d /home/daniel/.local/bin; and fish_add_path /home/daniel/.local/bin
test -d /home/daniel/.cargo/bin; and fish_add_path /home/daniel/.cargo/bin
test -d /home/daniel/go/bin; and fish_add_path /home/daniel/go/bin
set -gx EDITOR "vim"
